### ISSUE TITLE
NPE when adding an entry on the symbols tab in project properties after clicking Apply

### ISSUE THREAD

**Issue by 15knots** [15knots/cmake4eclipse#1]
java.lang.NullPointerException
	at de.marw.cdt.cmake.core.ui.CMakePropertyTab.saveToModel(CMakePropertyTab.java:197)
	at de.marw.cdt.cmake.core.ui.CMakePropertyTab.performApply(CMakePropertyTab.java:286)
	at org.eclipse.cdt.ui.newui.AbstractCPropertyTab.handleTabEvent(AbstractCPropertyTab.java:552)
	at org.eclipse.cdt.ui.newui.AbstractPage.forEach(AbstractPage.java:1055)
	at org.eclipse.cdt.ui.newui.AbstractPage$5.run(AbstractPage.java:672)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:69)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)

**Comment by 15knots** [comment]
fixed in 15knots@7d014f5b2cdc13a2c96c6185749d873e942cb872
