### ISSUE TITLE
incompatible with Eclipse Version 2021-06

### ISSUE THREAD

**Issue by gagarinlg** [15knots/cmake4eclipse#159]
When trying to buld a project with CMake4Eclipse from the market place in Eclipse 2021-06 this error message appears:

Errors occurred during the build.
Errors running builder 'CDT Builder' on project 'xxxxxx'.
Unexpcted/incorrect call to old clean method. Client code must call clean(Map,IProgressMonitor)

**To Reproduce**
open CMake4Eclipse enabled project
build project

**Expected behavior**

**Screenshots**

**Useful Information**
- cmake4eclipse version: 
  - cmake4eclipse	2.1.4.202105301214	
- Which OS do you use: 
  - Ubuntu Linux 20.04
- Cmake version: 
  - 3.16.3

**Comment by gagarinlg** [comment]
Turned out that this is an internal CDT Problem:
java.lang.IllegalStateException: Unexpcted/incorrect call to old clean method. Client code must call clean(Map,IProgressMonitor)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.clean(CommonBuilder.java:1039)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performCleanning(CommonBuilder.java:972)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performPrebuildGeneration(CommonBuilder.java:868)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:754)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:517)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:463)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:516)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:413)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

so I close the issue

**Comment by gagarinlg** [comment]
one last comment:
with Eclipse CDT 10.3.3 the error is fixed and will also be fixed in CDT 10.4.1

**Comment by 15knots** [comment]
Thank for reporting it at CDT.
