### ISSUE TITLE
NPE when managing multiple configurations

### ISSUE THREAD

**Issue by 15knots** [15knots/cmake4eclipse#201]
**Describe the bug**

When editing project properties for multiple configurations or all configurations and the Apply and Close button is pressed, cmake4eclipse throws an NPE, see below.

**Useful Information**
- cmake4eclipse version: 4.x, 5.x
 
***What is in Eclipse's Error Log?***
java.lang.NullPointerException: Cannot invoke "org.eclipse.cdt.core.settings.model.ICStorageElement.setAttribute(String,String)" because "parent" is null
    at de.marw.cmake4eclipse.mbs.settings.CMakeSettings.saveToStorage(CMakeSettings.java:156)
    at de.marw.cmake4eclipse.mbs.ui.CMakePropertyTab.persist(CMakePropertyTab.java:447)
    at de.marw.cmake4eclipse.mbs.ui.CMakePropertyTab.performOK(CMakePropertyTab.java:423)

**Comment by 15knots** [comment]
Fixede in cdba6866d31e8bec6669b4451d671d7de12a976d
