### ISSUE TITLE
No content.xml file in comp-update - Eclipse cannot install the plugin

### ISSUE THREAD

**Issue by kamilosxd678** [15knots/cmake4eclipse#49]
I am trying to install the newest version of the plugin into Eclipse Oxygen, but the loading takes forever and when it is finally over - I get the message that file https :// raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/content.xml could not be found (which is reasonable, as it is not there).

**Comment by 15knots** [comment]
The missing content.xml is not an error.
The file p2.index at the same location tells the installer to use compositeContent.xml instead.
I guess, githib was not reachable (or at least the p2.index) and your installer did fall back to fetch content.xml, which wasn`t found either.
Simply try again to install.

If the problem persists (works fine here), please post the relevant messages from the Eclipse error-log here.

**Comment by kamilosxd678** [comment]
I'm sorry, but it would seem that the eclipse does not know that it should work and does not.

![image](https://user-images.githubusercontent.com/3920932/31326762-811d9782-acca-11e7-844b-fd7e6869e0d8.png)

`Unable to read repository at https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/content.xml.`

`java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:542)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1.connectSocket(SNIAwareHttpClient.java:64)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`

**Comment by kamilosxd678** [comment]
Btw, do you have it working on Eclipse Oxygen or an older version?

**Comment by 15knots** [comment]
Am Montag, 9. Oktober 2017, 07:38:05 CEST schrieb kamilosxd678:
> Btw, do you have it working on Eclipse Oxygen or an older version?

Works with eclipse Oxygen here.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by 15knots** [comment]
Proxy settings? URL blocked?
Can you download the file `http://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/compositeContent.xml` with wget or curl? According to my wireshark log, `compositeContent.xml` is the second file that eclipse tries to fetch (first is `compositeContent.jar`, but that does not exist).

**Comment by 15knots** [comment]
Closing as not primarily related to the plugin
