### ISSUE TITLE
No error message in build log, when cmake executable could not be found

### ISSUE THREAD

**Issue by 15knots** [15knots/cmake4eclipse#51]
Just an entry in the eclipse log, which is not very helpful.

`java.io.IOException: Cannot run program
"C:\msys64\usr\bin\cmake.exeC:\msys64\usr\bin\cal.exeC:\msys64\usr\bin\cmake":
Launching failed
        at org.eclipse.cdt.utils.spawner.Spawner.exec(Spawner.java:349)
        at org.eclipse.cdt.utils.spawner.Spawner.<init>(Spawner.java:91)
        at
org.eclipse.cdt.utils.spawner.ProcessFactory.exec(ProcessFactory.java:91)
        at org.eclipse.cdt.core.CommandLauncher.execute(CommandLauncher.java:194)
        at
de.marw.cdt.cmake.core.internal.BuildscriptGenerator.invokeCMake(BuildscriptGenerator.java:312)
        at
de.marw.cdt.cmake.core.internal.BuildscriptGenerator.regenerateMakefiles(BuildscriptGenerator.java:236)
        at
de.marw.cdt.cmake.core.internal.BuildscriptGenerator.generateMakefiles(BuildscriptGenerator.java:148)
        at
org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performMakefileGeneration(CommonBuilder.java:1008)`

**Comment by 15knots** [comment]
Actually the message **is** in the build log, but if multiple projects are build, the message is lost when the a new console has opened.
The solution is to add marker to the problem view.
