### ISSUE TITLE
NPE when running builder 'CDT Builder' on project '...'.

### ISSUE THREAD

**Issue by eyck** [15knots/cmake4eclipse#78]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
When invoking the build for a project clean project the build failes with the message above

### What is the expected behavior?
the diectories get generated and the build starts

### What behavior are you observing?
When invoking the build for a project clean project the build failes with the message above. Looking into the error log the following log is there
```
java.lang.NullPointerException
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.getCommandFromCMakeCache(CmakeBuildRunner.java:169)
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.invokeBuild(CmakeBuildRunner.java:115)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:753)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:510)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:459)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:285)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```
Looking at the source code the comment in line 166 is not correct. The javadoc of IResource at http://help.eclipse.org/oxygen/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/IResource.html#getLocation-- states:
```
Returns:
    the absolute path of this resource in the local file system, or null if no path can be determined

```
so eventually a null-check is missing.

### Provide the steps to reproduce the issue, if applicable:
1. import cmake-based C++ project 
2. click build

## Useful Information
This is the product configuration:
```
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product
```
de.marw.cdt.cmake.feature.group version is 1.11.0.201802241905	
Cmake version: 3.9.2

**Comment by BerndDoser** [comment]
I see the same behavior for a new project. After starting cmake manually the build works also using cmake4eclipse.

I am using
 * eclipse 4.7.3
 * CDT 9.4.3.201802261533 org.eclipse.cdt.feature.group
 * cmake 3.11.1
 * openjdk-8-jdk
 * cmake4eclipse 1.11.0.201802241905 de.marw.cdt.cmake.feature.group

within a docker container, which can be started by
```
docker run -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY braintwister/ubuntu-16.04-cmake-3.11-gcc-7-conan-1.2-docker-18.03-eclipse-cpp-4.7.3
```

Please find more informations about eclipse in docker at https://github.com/BrainTwister/docker-devel-env#eclipse-ide-for-c-development

**Comment by 15knots** [comment]
@eyck, @BerndDoser: Simply avoiding the NPE and aborting any build would not make much sense IMHO.
Does the NPE happen on **each** build or on the **first one** only?

**Comment by BerndDoser** [comment]
The NPE happen on each build until I have started cmake manually.
I get a different stacktrace from @eyck:

```
java.lang.NullPointerException
	at org.eclipse.cdt.docker.launcher.ContainerCommandLauncherFactory.getCommandLauncher(ContainerCommandLauncherFactory.java:45)
	at org.eclipse.cdt.core.CommandLauncherManager.getCommandLauncher(CommandLauncherManager.java:178)
	at org.eclipse.cdt.core.CommandLauncherManager$CommandLauncherWrapper.execute(CommandLauncherManager.java:138)
	at de.marw.cdt.cmake.core.internal.BuildscriptGenerator.invokeCMake(BuildscriptGenerator.java:350)
	at de.marw.cdt.cmake.core.internal.BuildscriptGenerator.regenerateMakefiles(BuildscriptGenerator.java:275)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performMakefileGeneration(CommonBuilder.java:1006)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.performPrebuildGeneration(CommonBuilder.java:873)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:748)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:510)
	at org.eclipse.cdt.managedbuilder.internal.core.CommonBuilder.build(CommonBuilder.java:459)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:285)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by 15knots** [comment]
@BerndDoser:  That is exactly the NPE I see when the build is run with CDT docker launcher (as asked for in my PM to you). This seems to be a different issue, the NPE in this issue happens **after** cmake has been invoked, your NPE happens earleir, when cmake gets called.
Do you really run eclipse inside the docker container?

**Comment by eyck** [comment]
@15knots: Well, in principle you are right and I would assume the same but obviosly it returns null. I think the issue arises if the folder is referenced thru a path with a symbolic link. I have a symbolic link $HOME/git pointing to /shared/eyck/git and if I import a project from $HOME/git/<project dir> then the effective filepath /shared/eyck/git/<project dir/build/Debug) which is not within the project (/home/eyck/git/<project dir>/build/Debug). If I remember correctly I saw a similar issue in the issue tracker... And you are right, aborting the build is not a solution - I just saw the check and assumed that you have something in the caller implemented to work around this. The NPE perists unitl I run cmake on command line (and it happened that I even than still saw an -or the same- issue).

I noticed the problem when I started to play with GNU MCU maybe there is some twist between the two...

Anyways, I'm planning to clone the repo and dig a bit into the problem and other issues, I know sometimes it is very difficult to reproduce reported issues. Moreover I did encountered a few more things like I always need to explicitly select the CMAKE_EXPORT_COMPILE_COMMANDS parser as language settings provider. Cmake4eclipse is a great product and I like it pretty much as it addresses a need of me (I have conan integrated into the cmake setup and this way I get automatically all the conan packages referenced in eclipse). Maybe I have next week some time to set the environment up and have a look into it.

**Comment by 15knots** [comment]
I now managed to reporduce the NPE
```
java.lang.NullPointerException
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.getCommandFromCMakeCache(CmakeBuildRunner.java:169)
	at de.marw.cdt.cmake.core.internal.CmakeBuildRunner.invokeBuild(CmakeBuildRunner.java:115)
```
A fix could be to abort the build the; users will have to check their setup and/or project settings then.

**Comment by eyck** [comment]
In principle I agree: aborting is ok. But it should abort with a meaningful message. Otherwise this would not really be an improvment...
